---

#Configuring apache2
- name: copy apache2 configuration file on Ubuntu
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf
  when: ansible_os_family == "Ubuntu"
  enabled: yes
  notify: restart apache service

- name: enable and restart httpd on Centos
  when: ansible_os_family == "Centos"
  enabled: yes
  notify: restart httpd service

- name: create the webpage index.html
  copy: src=index.html dest=/var/www/html/index.html
  when: ansible_os_family == "Ubuntu"

- name: copy the image resource
  copy: src=Blue_marble_2015.jpg dest=/var/www/html/Blue_marble_2015.jpg
  when: ansible_os_family == "Ubuntu" 
  
  
