---

- name: start apache2 server
  service: name=apache2 state=started
  when: ansible_os_family == "Ubuntu"

- name: start httpd server
  service: name=httpd state=started
  when: ansible_os_family == "Centos"
